name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-modules:
    name: Setup Modules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global http.version HTTP/1.1
        git config --global url."https://".insteadOf git://

    - name: Clone required modules
      run: |
        echo "Cloning module1..."
        git clone https://github.com/tumusx/ci-cd-module.git 
    
    - name: Build AAR
      run: | 
        echo "Modules cloned successfully."
        cd modules/core && ./gradlew clean assembleDebug
    
    - name: Save AAR artifact
      uses: actions/upload-artifact@v3
      with:
          name: module1-debug-aar
          path: modules/core/module1/build/outputs/aar/module1-debug.aar
  

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: 31.0.0
        ndk: "23.1.7779620"

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build Project
      run: ./gradlew assembleDebug

