name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-modules:
    name: Setup Modules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global http.version HTTP/1.1
        git config --global url."https://".insteadOf git://

    - name: Clone required modules
      run: |
        echo "Cloning module1..."
        git clone https://github.com/tumusx/ci-cd-module.git modules/module1
        echo "Modules cloned successfully."
    
    - name: Build AAR
      run: | 
         echo "Building AAR module"
         cd modules/module1 && ./gradlew assembleDebug
         if find build -name "module1-debug.aar" | grep -q "module1-debug.aar"; then
          echo "AAR do core gerado com sucesso!"
         else
          echo "Erro: AAR do core não foi gerado."
          exit 1
          fi

  build:
    name: Build Android Project
    runs-on: ubuntu-latest
    needs: setup-modules

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: 31.0.0
        ndk: "23.1.7779620"

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build Project
      run: ./gradlew clean assembleDebug